### ISSUE TITLE
PHPDotEnv 5.5 compatibility

### ISSUE THREAD

**Issue by bwp-codes** [aprivette/bedrock-auth#1]
Hi Adam,
first off, thanks for this plugin!
I have noticed that it is currently not compatible with vlucas/phpdotenv v5.5 and throws some fatal errors regarding phpdotenv internals. I created a fork and changed some things to make it work, that I would like to share with you:

1: bedrock-auth.php:15-18
```
namespace BedrockAuth;

use Dotenv;
use Env;
```
changed to 
```
use function Env\env;
```

2: changed constructor from:
```
    public function __construct()
    {
        $this->root_dir = dirname(dirname(ABSPATH));
        $this->dotenv = new Dotenv\Dotenv($this->root_dir);

        Env::init();
    }
```
to:
```
    public function __construct()
    {
        $this->root_dir = dirname(dirname(ABSPATH));
        $this->dotenv = Dotenv\Dotenv::createUnsafeImmutable($this->root_dir);
    }
```

After these changes, the plugin can be activated when using with vlucas/phpdotenv v5.5

**Comment by aprivette** [comment]
Hey! Thanks for the notes, I just tagged a new release :)
